"""fix_relationships

Revision ID: 15792e1e9c6f
Revises: c021962db99b
Create Date: 2026-03-12 23:22:29.749632

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "15792e1e9c6f"
down_revision: Union[str, Sequence[str], None] = "c021962db99b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
